### PR TITLE
Add open governance model

### PR DESCRIPTION
**Pull request by gabor-boros**
## Description
The following pull request is a **proposal** of the Open Governance Model, which could help RethinkDB's community and decision-making process to avoid the "wild-west" situations.

The intention behind the proposal is to make it clear and understandable for new contributors and even existing ones how to help the project and how can they influence the future of the community.

The proposal describes the different participants of the community within the "Roles and responsibilities." It also explains how the decision-making process works, which involves the whole community about non-sensitive discussions like legal matters, vulnerability reports, and some strategic planning.

## Explaining your ideas
In case you feel that you do not agree with the proposal, feel free to comment on a specific sentence to have a discussion about it.

## Notes
If you like the proposal, please use the "like" (or similar) emoji to express your feelings about this proposal. This helps our work when we collect feedback about it. Also, if you don't agree with the proposal, please let us know publicly on this PR to have a discussion about it.

This is hard to read this amount of text in Markdown format. We know. Here you can check how it would be shown on the website if the proposal is accepted:  https://deploy-preview-254--rethinkdb.netlify.com/open-governance/

### CODE REVIEW

**Comment by srh** [comment]
Meanwhile https://github.com/rethinkdb/rethinkdb/ still has a link to a broken incomplete PHP driver, that just mysteriously appeared in the commit log.  If you want to avoid problems like that, just revert the commit that made it, don't have a 3 day waiting period to get anything done.   That's not going to speed up development on RethinkDB.

**Comment by mwakerman** [comment]
As (seemingly) the last original dev still interested in the project, I'd be interested in understanding why @srh thumbed-down the first comment on this issue.

**Comment by srh** [comment]
It seems like playing house to me.

The users already get consulted about what they'd like in terms of RethinkDB features when it matters, e.g. with respect to API changes or details of write hooks when the problems with `r.now()` were found.  Or most recently on removing the update checker, because it's not 100% obvious that's what's wanted.

I see no connection between having a document like this and getting actual stuff done in RethinkDB that puts features and fixes in the hands of users.  Users?  Contributors?  Committers?  Nomination processes to give people statuses?  It's a bunch of fluff totally inappropriate for a halfway dead project.

**Comment by srh** [comment]
Here's what you should do:  Have it be wild west, and if there's a problem, boros or whoever solves it.  Easy peasy.

**Comment by gabor-boros** [comment]
Hello @srh,

> just revert the commit that made it, don't have a 3 day waiting period to get anything done

Yes. You are right. In case of situations like this or similar, it requires immediate action. Waiting three days for the community to make sure they agree with removing a bad commit just makes no sense.

Just to give some context for everyone, this is the referenced sentence:
> For lazy consensus to be effective, it is necessary to allow at least 72 hours (3 days) before assuming that there are no objections to the proposal.

By this, we didn't mean to start pointless discussions about obvious things. This was for those discussions that we already have about the update checker, as you mentioned or this document. This document is not for changing something that already works but to write it down and be a bit more visible towards the community.

> I see no connection between having a document like this and getting actual stuff done in RethinkDB that puts features and fixes in the hands of users. Users? Contributors? Committers? Nomination processes to give people statuses?

I would like to highlight that this proposal is not about labeling people or putting statuses next to their name. I'm more than happy to remove nomination related things because the point here would be to have a common understanding of how everyone can contribute to the project. Every community needs some guidance because the lack of it will result in situations where nobody can do anything because of waiting for others. This is the only reason why the project management committee and PMC Chair is proposed in the document. Also, the PMC chair is only needed to ensure that all governance processes are adhered to and has the casting vote when RethinkDB fails to reach consensus. And of course, help others.

> It's a bunch of fluff totally inappropriate for a halfway dead project.

Although the project was nearly dead some months ago, as I can see, we were able to bring it back to life from lots of different points of view. We have a community that is more active day-by-day on several platforms and we got ~14  volunteers to help the project. - who will be contacted soon I promise. The point here is that we are getting back to life and by the release of 2.4.x we expect a lot bigger attraction which can easily result in unmanageable situations and this is what we would like to avoid.

As I mentioned earlier, the intention behind the proposal is to make it clear and understandable for new contributors and even existing ones how to help the project and how can they influence the future of the community.

(Sorry this became long)

**Comment by lsabi** [comment]
I would add that also users may report bugs, as they are the ones using the database in production and may discover bugs not known to the community. Also, users may ask for new features that they need, keeping the database relevant. If the feature request is accepted, that should depend on the contributors and higher levels.

**Comment by gabor-boros** [comment]
@lsabi absolutely agreed.

**Comment by srh** [comment]
My negative feedback is about, aside from the expression of a general cloud of negativity in my personality, has nothing, or little, to do with the contents of this document.  Well, I could find all sorts of criticisms about it; it is long and written by the sort of person who likes to say "consensus".

My real dissatisfaction is that you could being doing other stuff, like: releasing 2.4.  You could build the packages for the release candidate and release the release candidate.  Then release 2.4.  Nothing is stopping you!  You can do this right now. Release 2.4, and get write hooks and some other bug fixes in people's hands.  Instead, we have stuff that isn't releasing 2.4.

As for the governance model:

---

(Tl;dr: Remove committers and committer voting, make the PMC able to replace the chair with a simple majority.)

As for the governance model, my advice is to just have a PMC (with at least 3 people) and a PMC Chair chosen by simple majority of the PMC (not 2/3 majority, because that in this case would most likely unduly empower an incumbent chair).  That handles the problem where the PMC Chair gets hit by a bus or gets a brain tumor and goes rogue.

And:

> The PMC Chair has no additional authority over other members of the PMC: the role is one of coordinator and facilitator.  The Chair is also expected to ensure that all governance processes are adhered to and has the casting vote when RethinkDB fails to reach consensus.

I'd like to point out that these two sentences directly contradict each other.  This really means is that the Chair and the 1/3 PMC minority backing him/her holds all the cards.

All a governance model needs to do is specify what ultimately determines the content of releases, the website, copyright stuff, etc etc, and prevent a malicious actor from taking things off the rails: the fact that a decision must be made when people disagree.  You just need a PMC Chair and the PMC to do that.

It's a bad idea to have officially designated committers voting.  If the PMC Chair isn't listening to them anyway, then either the committers are wrong, or they're right and they can convince the PMC to replace or pressure the PMC Chair, or they can fork the project.  (I'll note that in the open governance model, the committers' voting power is totally illusory.  Since the PMC could kick out any committer, committer voting is just a way for committers to express their opinion; they have no actual power, besides the soft power of threatening to fork the project, which they have in any case.)

So, trimming down the document a bit, I'd recommend something that has the power structure except 51% instead of 67% majority, and no need to waste time voting on committers who have no real power anyway:

----

Clopen Governance Model

# Overview

Anyone with an interest in RethinkDB can contribute to RethinkDB design and development and participate in the decision-making process.  This document describes how that participation takes place.

# Roles and responsibilities

## Project Management Committee

The project management committee (PMC) consists of those individuals identified as ‘project owners.’  PMC members are expected to review code contributions, participate in strategic planning, approve changes to the governance model and manage the copyrights within RethinkDB outputs.

The PMC members have access to RethinkDB’s private private communication channels, and its archives.  These communication platforms are used for sensitive issues, such as legal matters, vulnerability reports, and any other matters that cannot be discussed in public.

Membership of the PMC is by invitation from the existing PMC members.  A nomination will result in discussion and then a vote by the existing PMC members.  The addition of a new PMC member may be vetoed by any existing PMC member.

## PMC Chair

The PMC Chair is a single PMC member voted for by a simple majority of the PMC members. Once someone has been appointed Chair, they remain in that role until they choose to retire, or the PMC casts a simple majority vote to replace them.

The Chair is expected to ensure that all governance processes are adhered to.  The Chair has the casting vote when the PMC fails to reach a consensus on any decisions, except for issues on which the PMC must hold, or chooses to hold, a formal vote, in which case, the Chair has the casting vote when the PMC fails to reach a simple majority.

## Everybody Else

This consists of people who are not PMC members.

# Decision-making process

Decisions about the future of RethinkDB should be made through discussion with anybody who wants to contribute. All non-sensitive project management discussion should take place in a public discussion channel, and for important decisions, people should be given enough time to participate.

In order to ensure that RethinkDB is not bogged down by endless discussion and continual voting, final authority on decisions goes to the PMC.

This allows the majority of decisions to be made without resorting to a formal vote.

Issues such as those affecting the strategic direction or legal standing of RethinkDB must gain explicit approval in the form of a vote by the PMC.  The PMC must have at least 3 members when it holds such a vote.  The PMC may also choose to hold a formal vote on other issues.  Everybody else is encouraged to express their opinions in all discussions and all votes.  However, only PMC members have binding votes for the purposes of decision making.

**Comment by srh** [comment]
You should also understand that there is no reason you should listen to my opinion, unless it's persuasive and convincing, because your choices about stuff like this have no effect on what I do.

**Comment by gabor-boros** [comment]
@srh, I can see most of the motivation behind what you wrote, and I appreciate that you explained them. I would never think about a PMC Chair could ever use the 2/3 to form a situation where she/he can not be replaced, or PMC could keep its position by kicking out committers.

The whole point of the document was not to create a possible situation where the suggestions can be abused but help everyone, so I'm currently reworking those parts of the document based on your suggestions.

**Comment by gabor-boros** [comment]
@srh @KittyBot If I missed something from the document or forgot to rephrase a sentence, please let me know.

@srh If you find anything which can affect us in a negative way in the future (like the 2/3 majority voting), please let me know and I'll adjust that as soon as I can.

Waiting for your feedback :blush:

**Comment by gabor-boros** [comment]
@lsabi I added "requesting new features" to users, but did not add bug reports since then it is a contribution, and at that point, we should handle them as contributors, if that makes sense to you.

**Comment by lsabi** [comment]
@gabor-boros it's some sort of gray area in my opinion. On the one hand it makes sense to me as non contributors may be using the system in a naive way with possibly wrong configurations, while on the other hand I reported bugs in projects where I was not a contributor, just using it.

My reason is that, for instance, if the database tests arrive to "just" 100 GB of disk space while a user is using 250 GB, he/she may discover a bug such as number overflow or similar. And this is something that users have to be able to report. I guess that at that size the user is probably a contributor or similar, but still we cannot be sure.

A possible solution would be to allow anyone to report bugs during the rebirth phase (i.e. this one), so that the community can grow and the system get improvements, while restricting bug reporting once the community is big and stable enough.

I hope you can understand my point and if there are any further suggestions or doubts on how to handle such situation, we can discuss them (possibly copying from other projects).

**Comment by gabor-boros** [comment]
@lsabi I just added bug reporting to users.

> possible solution would be to allow anyone to report bugs

I would like to highlight that none of the "roles" are limited. The users will be contributors at the moment when they report a bug or ask for a feature even if they are not the ones who will actually implement that. 

I think it is important to mention since nobody will be labeled or put into a category. 😊 I hope it makes sense. 

@srh, @KittyBot, @lsabi If there is no objection and everyone agrees with the current status of the document, I would say let's wait the 3 days and merge it by 5th of November. In case you have any concerns please let me know. 😊 🎉

**Comment by lsabi** [comment]
I know it's kinda obvious for everyone, but I would also add something like "All members of the project (including users and contributors) are supposed to agree and follow the rules regulating the contribution mechanism and the engagement with the community".

There may be a link or more to the contribution rules/guidelines. Does it fall into the governance model or in another section? I'm pointing this out because I don't see it (I may have misread or skipped a line).

**Comment by gabor-boros** [comment]
@lsabi Since the contribution guideline is a separate document and ~must~ should be read by every contributor, I would not put that part into this document to keep its size smaller.

**Pull request closed without merging**
