### PR TITLE
v2.4.4 announcement

### PR DESCRIPTION
**Pull request by srh**
cc @gabor-boros 

Note that compared to the v2.4.3 announcement, I dropped mention of Freenode.

**Checklist**
- [x] I have read and agreed to the [RethinkDB Contributor License Agreement](http://rethinkdb.com/community/cla/)

### CODE REVIEW

**Comment by srh** [comment]
It's unlear why the review checks failed, because I don't have access to see the logs.

**Comment by srh** [comment]
I did get it to build locally, though I had to `bundle add webrick` to get it working.  Maybe that has something to do with me using Linux instead of MacOS.

**Comment by gabor-boros** [comment]
@srh To me the local build (yesterday) worked with the changes I merged on macos without the `webrick` gem. The build logs are showing this:

```
6:01:42 AM: $ rake init && rake build
6:01:43 AM: Failed during stage "building site": Build script returned non-zero exit code: 2
6:01:43 AM: /opt/buildhome/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe": can"t find gem rake (>= 0.a) with executable rake (Gem::GemNotFoundException)
	from /opt/buildhome/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path"
	from /opt/buildhome/.rvm/rubies/ruby-2.7.8/bin/rake:29:in `<main>"
```

I'm not a Ruby guy at all, but can it happen that `rake` is not found? Out of curiosity I [restarted your build](https://app.netlify.com/sites/rethinkdb/deploys/65768e50096c7927bc73479e) and it passed, so I would say it is a flaky builder on Netlify's end. I'm going to merge this PR and restart the build of the master branch if it fails.

**Comment by srh** [comment]
@gabor-boros I restarted once, so that would make it 2 failed builds and 1 successful build in this PR.

I have no idea how Rake, the gem, could not be found.

Also, I'll note that locally, I was running Ruby 3.0.2 (the version that is distributed with Ubuntu 22.04).  Maybe that is why I had the `webrick` issue on my machine.

**Comment by srh** [comment]
The website is updated with the 2.4.4 release; thank you for merging this.

**Comment by gabor-boros** [comment]
The full truth is that I cleared the builder cache as well, so probably their cache was "corrupted". Ah, that's great to know that the site works with Ruby 3, the builders are running Ubuntu 20.04 and Ruby 2.7.x. Tomorrow I'll try to upgrade the ruby version of both the www (this) and docs repo as well. If that succeeds, I'll give a shot to update the dependencies as well.

**Pull request merged**
